name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build and push docker image
      run: |
        echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker pull hello-world:latest
        docker tag hello-world:latest docker.pkg.github.com/${{ github.repository }}/hello-world:latest
        docker push docker.pkg.github.com/${{ github.repository }}/hello-world:latest
